name: ydapp
description: yiddishland.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/1. Spash Screen (1).jpg
    - assets/1. Spash Screen (2).png
    - assets/1. Spash Screen (3).png

platforms:
  android:
  ios:
  web:
  macos:
  windows:
